resolver: lts-11.15

packages:
- .

- location:
    github: reflex-frp/reflex
    commit: df8152be4a585bbb72d8b087ebb88a5399a9cb1f  # develop on 2018.06.16
  extra-dep: true

extra-deps:
- ref-tf-0.4.0.1
